# Generated by Django 5.2.1 on 2025-06-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteafr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.PositiveIntegerField()),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
